#!/usr/bin/env python3
"""
Launch Tera Term on the machine hosting the dashboard.

The dashboard is normally run on the operator's own Windows PC, so clicking
"Tera Term" in the browser can open a real terminal session to the device
using the credentials already stored in the inventory.

Two ways to start a session:

* a `.ttl` macro (default) — keeps the password out of the Windows process
  list, and also handles Telnet auto-login prompts
* direct command line — no temp file, but the password is visible in the
  process list

If Tera Term is not installed on this machine (for example the dashboard runs
on a Linux server), the endpoint returns the macro so the operator can run it
on their own PC instead.
"""

import os
import shutil
import subprocess
import tempfile


def find_teraterm(explicit: str = "", search_paths=()) -> str:
    """Locate ttermpro.exe, or return '' when it is not installed here."""
    if explicit and os.path.isfile(explicit):
        return explicit
    for path in search_paths:
        if os.path.isfile(path):
            return path
    return shutil.which("ttermpro") or shutil.which("ttermpro.exe") or ""


def find_macro_runner(teraterm_exe: str) -> str:
    """ttpmacro.exe lives next to ttermpro.exe."""
    if teraterm_exe:
        candidate = os.path.join(os.path.dirname(teraterm_exe), "ttpmacro.exe")
        if os.path.isfile(candidate):
            return candidate
    return shutil.which("ttpmacro") or shutil.which("ttpmacro.exe") or ""


def _quote(value: str) -> str:
    """Escape single quotes for Tera Term macro string literals."""
    return str(value or "").replace("'", "''")


def build_macro(dev: dict, transport: str) -> str:
    """Build a .ttl macro that connects and logs in."""
    host = _quote(dev.get("host", ""))
    port = int(dev.get("port") or (22 if transport == "ssh" else 23))
    user = _quote(dev.get("username", ""))
    password = _quote(dev.get("password", ""))
    enable = _quote(dev.get("enable_password", ""))

    lines = [
        "; Generated by Cisco Multi-Device Monitor",
        f"; Device: {_quote(dev.get('name', ''))}",
        "",
    ]

    if transport == "ssh":
        lines += [
            f"connect '{host}:{port} /ssh /2 /auth=password /user={user} /passwd={password}'",
        ]
    else:
        lines += [
            f"connect '{host}:{port} /nossh'",
            "wait 'sername:' 'ogin:' 'Password:'",
            f"sendln '{user}'",
            "wait 'assword'",
            f"sendln '{password}'",
        ]

    if enable:
        lines += [
            "wait '>' '#'",
            "sendln 'enable'",
            "wait 'assword'",
            f"sendln '{enable}'",
        ]

    lines.append("")
    return "\r\n".join(lines)


def build_command(dev: dict, transport: str, teraterm_exe: str) -> list:
    """Direct command line (password visible in the process list)."""
    host = dev.get("host", "")
    port = int(dev.get("port") or (22 if transport == "ssh" else 23))
    target = f"{host}:{port}"

    if transport == "ssh":
        return [
            teraterm_exe, target, "/ssh", "/2", "/auth=password",
            f"/user={dev.get('username', '')}",
            f"/passwd={dev.get('password', '')}",
        ]
    return [teraterm_exe, target, "/nossh"]


def launch(dev: dict, transport: str, explicit_exe: str = "",
           search_paths=(), use_macro: bool = True) -> dict:
    """Start Tera Term locally. Returns a result dict for the API."""
    macro = build_macro(dev, transport)
    teraterm_exe = find_teraterm(explicit_exe, search_paths)

    if not teraterm_exe:
        return {
            "ok": False,
            "launched": False,
            "error": "Tera Term not found on the machine running this dashboard",
            "macro": macro,
            "hint": (
                "Install Tera Term here, set the TERATERM_EXE environment "
                "variable, or download the macro and run it on your PC."
            ),
        }

    runner = find_macro_runner(teraterm_exe) if use_macro else ""

    try:
        if runner:
            handle, path = tempfile.mkstemp(prefix="ttl_", suffix=".ttl", text=True)
            with os.fdopen(handle, "w", encoding="utf-8") as fh:
                fh.write(macro)
            try:
                os.chmod(path, 0o600)
            except OSError:
                pass
            command = [runner, path]
        else:
            command = build_command(dev, transport, teraterm_exe)

        subprocess.Popen(command, close_fds=True)
        return {
            "ok": True,
            "launched": True,
            "method": "macro" if runner else "command line",
            "command": os.path.basename(command[0]),
        }
    except Exception as e:
        return {
            "ok": False,
            "launched": False,
            "error": f"{e.__class__.__name__}: {e}",
            "macro": macro,
        }
